import { Race } from './race-type';
import { BuildingType } from './building-type';

export const BUILDING_NAMES: Record<Race, Record<BuildingType, string>> = {
  [Race.HUMAN]: {
    [BuildingType.SAWMILL]: 'Lumber Mill',
    [BuildingType.CLAY_PIT]: 'Brickworks',
    [BuildingType.IRON_MINE]: 'Ironworks',
    [BuildingType.FARM]: 'Farmland',
    // … storage …
    [BuildingType.WAREHOUSE]: 'Storage Barn',
    [BuildingType.GRANARY]: 'Granary',
    [BuildingType.MARKET]: 'Market Square',
    // … military …
    [BuildingType.BARRACKS]: 'Barracks',
    [BuildingType.STABLE]: 'Stables',
    [BuildingType.WORKSHOP]: 'Siege Workshop',
    [BuildingType.WALL]: 'Stone Wall',
    [BuildingType.TOWER]: 'Watchtower',
    // … special …
    [BuildingType.SMITHY]: 'Blacksmith',
    [BuildingType.EMBASSY]: 'Embassy',
    [BuildingType.ACADEMY]: 'Academy',
    [BuildingType.SHRINE]: 'Shrine of Kings',
  },

  [Race.ORC]: {
    [BuildingType.SAWMILL]: 'Warwood Camp',
    [BuildingType.CLAY_PIT]: 'Mud Pits',
    [BuildingType.IRON_MINE]: 'Bone Mine',
    [BuildingType.FARM]: 'Warlord Fields',
    [BuildingType.WAREHOUSE]: 'Spoils Hoard',
    [BuildingType.GRANARY]: 'Meat Stash',
    [BuildingType.MARKET]: 'Trade Pit',
    [BuildingType.BARRACKS]: 'War Camp',
    [BuildingType.STABLE]: 'Beast Lair',
    [BuildingType.WORKSHOP]: 'Crushworks',
    [BuildingType.WALL]: 'Spiked Palisade',
    [BuildingType.TOWER]: 'Grudge Tower',
    [BuildingType.SMITHY]: 'Furnace of Blood',
    [BuildingType.EMBASSY]: 'Chieftain’s Hall',
    [BuildingType.ACADEMY]: 'Shaman’s Circle',
    [BuildingType.SHRINE]: 'Sacrificial Altar',
  },

  [Race.ELF]: {
    [BuildingType.SAWMILL]: 'Grove of Saws',
    [BuildingType.CLAY_PIT]: 'Clay Hollow',
    [BuildingType.IRON_MINE]: 'Silver Vein',
    [BuildingType.FARM]: 'Moonlight Fields',
    [BuildingType.WAREHOUSE]: 'Tree Cache',
    [BuildingType.GRANARY]: 'Cornucopia',
    [BuildingType.MARKET]: 'Sylvan Bazaar',
    [BuildingType.BARRACKS]: 'Ranger Lodge',
    [BuildingType.STABLE]: 'Swift Glade',
    [BuildingType.WORKSHOP]: 'Faeworks',
    [BuildingType.WALL]: 'Living Wall',
    [BuildingType.TOWER]: 'Starwatch Tower',
    [BuildingType.SMITHY]: 'Moonforge',
    [BuildingType.EMBASSY]: 'Council Glade',
    [BuildingType.ACADEMY]: 'Arcane Spire',
    [BuildingType.SHRINE]: 'Grove Shrine',
  },

  [Race.DWARF]: {
    [BuildingType.SAWMILL]: 'Stonecut Mill',
    [BuildingType.CLAY_PIT]: 'Ore Pit',
    [BuildingType.IRON_MINE]: 'Deep Iron Mine',
    [BuildingType.FARM]: 'Highland Farm',
    [BuildingType.WAREHOUSE]: 'Vault Depot',
    [BuildingType.GRANARY]: 'Stone Granary',
    [BuildingType.MARKET]: 'Iron Market',
    [BuildingType.BARRACKS]: 'Battle Hall',
    [BuildingType.STABLE]: 'Mountain Stables',
    [BuildingType.WORKSHOP]: 'Engine Works',
    [BuildingType.WALL]: 'Fortified Rampart',
    [BuildingType.TOWER]: 'Beacon Tower',
    [BuildingType.SMITHY]: 'Forge of the Ancients',
    [BuildingType.EMBASSY]: 'Dwarf Embassy',
    [BuildingType.ACADEMY]: 'Runecarver’s Hall',
    [BuildingType.SHRINE]: 'Hall of Stones',
  },

  [Race.UNDEAD]: {
    [BuildingType.SAWMILL]: 'Bone Mill',
    [BuildingType.CLAY_PIT]: 'Ghoul Pits',
    [BuildingType.IRON_MINE]: 'Necromine',
    [BuildingType.FARM]: 'Plague Fields',
    [BuildingType.WAREHOUSE]: 'Crypt Storage',
    [BuildingType.GRANARY]: 'Rotgranary',
    [BuildingType.MARKET]: 'Black Market',
    [BuildingType.BARRACKS]: 'Undead Barracks',
    [BuildingType.STABLE]: 'Nightmare Stables',
    [BuildingType.WORKSHOP]: 'Deathworks',
    [BuildingType.WALL]: 'Bone Wall',
    [BuildingType.TOWER]: 'Dark Spire',
    [BuildingType.SMITHY]: 'Soulforge',
    [BuildingType.EMBASSY]: 'Lich Council',
    [BuildingType.ACADEMY]: 'Necrotower',
    [BuildingType.SHRINE]: 'Shrine of the Damned',
  },
};
